name: hello-nam
base: core22
version: '1.0'
summary: Simple Hello Nam application
description: |
  This is a simple Hello World application to demonstrate how to create a Snap.

confinement: devmode

parts:
  hello-nam-test:
    plugin: colcon
    source-type: git
    source: https://github.com/cedricnam/devv.git
    source-branch: master
    source-subdir: res
    stage-packages:
      # - ros-humble-ros2launch
      - ros-humble-ros2run
      - ros-humble-std-msgs

apps:
  hello-nam:
    command: opt/ros/humble/bin/ros2 run res res
    extensions: [ros2-humble]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LANG: en_US.UTF-8