name: hello-nam
base: core22
version: '1.0'
summary: Simple Hello Nam application
description: |
  This is a simple Hello World application to demonstrate how to create a Snap.

# grade: stable
confinement: dev-mode

parts:
  hello-nam:
    plugin: colcon
    source-type: git
    source: https://github.com/cedricnam/devv.git
    source-branch: master
    source-subdir: devv_launch
    stage-packages: [ros-humble-ros2launch]

apps:
  hello-world:
    command: opt/ros/humble/bin/ros2 launch devv_launch devv_launch.py
    extentions: [ros2-humble]
