name: hello-nam
base: core20
version: '1.0'
summary: Simple Hello Nam application
description: |
  This is a simple Hello World application to demonstrate how to create a Snap.

confinement: devmode

parts:
  hello-nam-test:
    plugin: colcon
    source-type: git
    source: https://github.com/cedricnam/devv.git
    source-branch: master
    source-subdir: res
    stage-packages:
      # - ros-foxy-ros2launch
      - ros-foxy-ros2run
      - ros-foxy-std-msgs
  pymongo:
    plugin: python
    source: /home/rtr/.local/lib/python3.8/site-packages
    stage-packages:
      - python3-pymongo

apps:
  hello-nam:
    command: opt/ros/foxy/bin/ros2 run res res
    extensions: [ros2-foxy]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LANG: en_US.UTF-8